language: node.js
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: nathan@cascade-softworks.com
  on:
    tags: true
  api_key:
    secure: 3V3ZJoPcplV9p2i04UPdawXfAldz5M/j0qAXd5FPpOnBOsPW4//heg3MxY/NSyLxbvQlmO24uKezWi1SN27Q5ixtbiBJVm391C/5swSDxWa9AdHIC3+hYuFaYyrXc85YXPveOPBR3QVtpfy54GmDrsUam68TRt6d7H4lSwfuxk3ajSnzaSvfSjCO2c8YwRjmZ4XjZYlcpqZ7YcsC7NUgBDzLSq2gjI8y3LoMOCWutcPLrbCitRPYak5LSlK3/tjb6sDAfOOB/5PqmN1dWoDM9a49WSFLwpYxF8o7+eH47dBiRzSX/M4HeDDU2lKZl/mniyry3L4ftdgRQs4/xmx+SeTY/+9oxZqAz52G3J9OZeQcP2VX4OFgdKCmymaupQhVG0SRbXmqIv+2h1s7Ku+ai9EwbF067UYXF8RE+Mn8YsvfK3jGG3dVZ4hubcv+mkg+IqdP4WQiftsPZA90Uo3frx3EHZIhbLIbxkvA9ZK39VD954YSj93g8itUXcVfUK3gU9hde6EfHEFT2lS2V3ov+K8VWxQHZY8GJqtHdsfkZbzag4kRBYr5xgrwcebmHf03itxSw5d6aR6BKmhAujxxP2X2cT704yuOs6gYbpy+UyeoeFndm8mKkG4+yDhNeLA+4/tz5OhJZstF41+kce9ifFog4q5DNT4wVKexC/K7g+w=
  